out/production/Ruby_Rails_project/config/routes.rb
Rails.application.routes.draw do

  resource :registrations, only: [:new, :create]

  resource :sessions, only: [:new, :create, :destroy]

  resource :settings, only: [:edit, :update]

  resources :users, only: [:index, :show]

  resources :tweets

  root to: "top#index"
end

out/production/Ruby_Rails_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

out/production/Ruby_Rails_project/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: {in: 1..140}

  default_scope -> { order(created_at: :desc) }
end

out/production/Ruby_Rails_project/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :tweets, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z][a-z0-9]+\z/ }, length: { in: 4..24 }
  validates :screen_name, length: { maximum: 140 }
  validates :bio, length: { maximum: 200  }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { in: 6..24 }, if: :password
  validates :password_confirmation, presence: true, if: :password
end

out/production/Ruby_Rails_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

out/production/Ruby_Rails_project/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new( params_user )

    if @user.save
       login(@user.email, @user.password)
       redirect_to root_url
    else
      render  :new
    end
  end

  private

  def params_user
    params.require(:user).permit(:name, :email ,:password, :password_confirmation)
  end
end

out/production/Ruby_Rails_project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    email    = params_user[:email]
    password = params_user[:password]

    if login(email, password)
       redirect_to users_path, notice: "サインインしました"
    else
       @user = User.new(email: email)
       render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, notice: "サインアウトしました"
  end

  private

  def params_user
    params.require(:user).permit(:email, :password)
  end

end

out/production/Ruby_Rails_project/app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes( params_user )
      redirect_to user_url(@user), notice: "プロフィールを更新しました"
    else
      render :edit
    end
  end

  private

  def params_user
    params.require(:user).permit(:name, :screen_name, :bio)
  end
end

out/production/Ruby_Rails_project/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    # @message = "おはようございます！"
    # @description = "これからRailsアプリケーションを作ります。"
    # @maxlength = @description.length
  end
end

out/production/Ruby_Rails_project/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_login,except: [:index]
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        @tweets = Tweet.all
        format.html { render :index }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

out/production/Ruby_Rails_project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

out/production/Ruby_Rails_project/app/helpers/application_helper.rb
module ApplicationHelper
end

out/production/Ruby_Rails_project/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

out/production/Ruby_Rails_project/app/helpers/sessions_helper.rb
module SessionsHelper
end

out/production/Ruby_Rails_project/app/helpers/settings_helper.rb
module SettingsHelper
end

out/production/Ruby_Rails_project/app/helpers/tweets_helper.rb
module TweetsHelper
end

out/production/Ruby_Rails_project/app/helpers/users_helper.rb
module UsersHelper
  def render_user_screen_name user
    if user.screen_name.blank?
      user.name
    else
      user.screen_name
    end
  end
end

out/production/Ruby_Rails_project/app/views/layouts/_header.html.slim
.navbar.navbar-light.bg-light
  .container-fluid
    .navbar-collapse
    = link_to '#DemoSite', root_url, class: "navbar-brand"

    - if logged_in?
      ul.nav.ml-auto
        .navbar-nav.nav-item
        li= link_to "全ツイート一覧", tweets_path, class: "navbar-right"
        .navbar-nav.nav-item
        li= link_to "ユーザー一覧", users_path, class: "navbar-right"
        .navbar-nav.nav-item
        li= link_to current_user.name, current_user, class: "navbar-right"
        .navbar-nav.nav-item
        li= link_to "設定", edit_settings_path, class: "navbar-right"
        .navbar-nav.nav-item
        li= link_to "ログアウト", sessions_path, method: :delete

    - else
      ul.nav.ml-auto
        .navbar-nav.nav-item
        li= link_to "会員登録", new_registrations_path, class: "navbar-right"
        .navbar-nav.nav-item
        li= link_to "ログイン", new_sessions_path

out/production/Ruby_Rails_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyRailsProject</title>
    <%= stylesheet_link_tag    'application', :debug => true , media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', :debug => true , 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body id="application">
    <div>
      <%= render partial: "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

out/production/Ruby_Rails_project/app/views/layouts/registrations.html.slim
doctype html
head
  title DemoSite SignUp
  = stylesheet_link_tag 'registrations', :debug => true , media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', :debug => true , 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
body
  meta charset="utf-8"
  #registrations
    = yield

out/production/Ruby_Rails_project/app/views/layouts/sessions.html.slim
doctype html
head
  title DemoSite Login
  = stylesheet_link_tag 'sessions', :debug => true , media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', :debug => true , 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
body
  meta charset="utf-8"
  #sessions
    = yield

out/production/Ruby_Rails_project/app/views/layouts/settings.html.slim
doctype html
head
  title DemoSite settings
  = stylesheet_link_tag 'settings', :debug => true , media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', :debug => true , 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
body
  meta charset="utf-8"
  = render partial: "layouts/header"
  #settings
    = yield

out/production/Ruby_Rails_project/app/views/layouts/tweets.html.slim
doctype html
head
  title DemoSite tweets
  = stylesheet_link_tag 'tweets', :debug => true , media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', :debug => true , 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
body
  meta charset="utf-8"
  = render partial: "layouts/header"
  = yield

out/production/Ruby_Rails_project/app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyRailsProject</title>
    <%= stylesheet_link_tag    'users', :debug => true , media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', :debug => true , 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body id="application">
    <div>
      <%= render partial: "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

out/production/Ruby_Rails_project/app/views/settings/edit.html.slim
#settings-edit
  .container
    .rom
      .col-lg-9.settings-content
        - @user.errors.each do |attr, message|
          .alert.alert-danger= message
        = form_for @user, url: settings_path, method: :put do |f|
          h2 設定
          .form-body
            .form-group
              = f.label :name, "ユーザーID: xxxxx@gmail.com",class: "control-label"
              = f.text_field :name, class: "form-control"
            .form-group
              = f.label :screen_name, "表示名: Test太郎", class: "control-label"
              = f.text_field :screen_name, class: "form-control"
            .form-group
              = f.label :bio, "プロフィール(200文字)", class: "control-label"
              = f.text_area :bio, class: "form-control"
            = f.submit "送信する", class: "btn btn-success"

out/production/Ruby_Rails_project/app/views/top/index.html.erb
<meta http-equiv="refresh" content="1; URL=http://localhost:3000/registrations/new">
<!-- <h1> <%= @message %> </h1>
<p> <%= @description %> </p>
<p> <%= @maxlength %> </p> -->

out/production/Ruby_Rails_project/app/views/tweets/_form.html.slim
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      ul
        - @tweet.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :content
    = f.text_field :content
  .actions = f.submit

out/production/Ruby_Rails_project/app/views/tweets/edit.html.slim
h1 Editing tweet

== render 'form'

=> link_to 'Show', @tweet
'|
=< link_to 'Back', tweets_path

out/production/Ruby_Rails_project/app/views/tweets/index.html.slim
#tweets-content
  .container
    .row
      .col-lg-4.left-content.border
        - if logged_in?
        .panel.panel-default
          .panel-body
            = link_to user_path(current_user), class: "user" do
              span.user-name
                = render_user_screen_name current_user
              span.user-id  @#{current_user.name}
            .user-activity
              .row
                .col-lg-4.tweets-num
                  .text つぶやき
                  .num
                    = link_to current_user.tweets.count, user_path(current_user)
                .col-lg-4.follow-num
                  .text フォロー
                  .num 0
                .col-lg-4.follower-num
                  .text フォロワー
                  .num 0
            - @tweet.errors.full_messages.each do |message|
              .alert.alert-danger= message
            = form_for @tweet do |f|
              #new_tweet.form-group
                = f.text_area :content, class: "form-control"
                = f.submit "つぶやく", class: "btn btn-success"

      .col-lg-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          = div_for @tweets, class: "list-group-item" do |t|
            h4.user
              span.user-name
                = link_to render_user_screen_name(t.user), user_path(t.user)
              span.user-id  @#{t.user.name}
              span.time.pull-right
                = distance_of_time_in_words_to_now(t.created_at)
              .clear
            .tweet-content
              p = t.content

out/production/Ruby_Rails_project/app/views/tweets/new.html.slim
h1 New tweet

== render 'form'

= link_to 'Back', tweets_path

out/production/Ruby_Rails_project/app/views/tweets/show.html.slim
p#notice = notice

p
  strong User:
  = @tweet.user_id
p
  strong Content:
  = @tweet.content

=> link_to 'Edit', edit_tweet_path(@tweet)
'|
=< link_to 'Back', tweets_path

out/production/Ruby_Rails_project/app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

out/production/Ruby_Rails_project/app/views/users/edit.html.slim
%h1 Editing user

= render 'form'

= link_to 'Show', @user

= link_to 'Back', users_path

out/production/Ruby_Rails_project/app/views/users/index.html.slim
.container-fluid
  .row
    .col-lg-10#users-content.border
      .list-group
        h2 ユーザー一覧
        = div_for @users, class: "list-group-item" do |u|
          h4.user.user-list
            span.user-name
              = link_to render_user_screen_name(u), user_path(u)
            span.user-id  @#{u.name}

          .bio
          = u.bio

out/production/Ruby_Rails_project/app/views/users/new.html.slim
%h1 New user

= render 'form'

= link_to 'Back', users_path

out/production/Ruby_Rails_project/app/views/users/show.html.slim
.container-fluid
  .row
    .col-lg-10#users-content.border
      .user-info
        - if notice
          .alert.alert-info= notice
        span.user-name
          = render_user_screen_name( @user )

        span.user-id  @#{@user.name}

      .bio
        = @user.bio

        ul.nav.nav-tabs.nav-justified
          li.active.nav-item = link_to user_path(@user) do
            .text つぶやき
            .num #{@user.tweets.count}
          li.nav-item = link_to nil do
            .text フォロー
            .num 0
          li.nav-item = link_to nil do
            .text フォロワー
            .num 0
          li.nav-item = link_to nil do
            .text お気に入り
            .num 0

      .list-group
        - if @user.tweets.empty?
          .list-group-item "まだツイートはありません"
        = div_for @user.tweets, class: "list-group-item" do |t|
          h4.user
            span.user-name
              = link_to t.user.name, user_path(t.user)
            span.user-id @#{t.user.name}

            span.time.pull-right
              = distance_of_time_in_words_to_now(t.created_at)
            .clear
          .tweet-content
          p
            = t.content